### ISSUE TITLE
ReferenceError: TransformStream is not defined

### ISSUE THREAD

**Issue by StevenBendell** [wehriam/remix-sse#1]
I tried to add this to my project and then tried the example project both produced the following error

`ReferenceError: TransformStream is not defined
    at new SseResponse (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@wehriam+remix-sse@1.0.4_react@18.2.0\node_modules\@wehriam\remix-sse\src\index.ts:38:36)
    at loader (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\app\routes\counter.ts:4:20)
    at Object.callRouteLoader (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+server-runtime@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\server-runtime\dist\data.js:72:20)
    at handleResourceRequest (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+server-runtime@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\server-runtime\dist\server.js:456:25)
    at requestHandler (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+server-runtime@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\server-runtime\dist\server.js:59:29)
    at C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+express@1.7.6_cwk4saenierp7pa7l5cpbeswge\node_modules\@remix-run\express\dist\server.js:39:28
    at C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+serve@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\serve\dist\index.js:48:7
    at Layer.handle [as handle_request] (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\route.js:144:13)
    at next (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\route.js:140:7)
GET /counter 500 - - 5.843 ms
GET / 200 - - 5.241 ms
ReferenceError: TransformStream is not defined
    at new SseResponse (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@wehriam+remix-sse@1.0.4_react@18.2.0\node_modules\@wehriam\remix-sse\src\index.ts:38:36)
    at loader (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\app\routes\counter.ts:4:20)
    at Object.callRouteLoader (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+server-runtime@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\server-runtime\dist\data.js:72:20)
    at handleResourceRequest (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+server-runtime@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\server-runtime\dist\server.js:456:25)
    at requestHandler (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+server-runtime@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\server-runtime\dist\server.js:59:29)
    at C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+express@1.7.6_cwk4saenierp7pa7l5cpbeswge\node_modules\@remix-run\express\dist\server.js:39:28
    at C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\@remix-run+serve@1.7.6_biqbaboplfbrettd7655fr4n2y\node_modules\@remix-run\serve\dist\index.js:48:7
    at Layer.handle [as handle_request] (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\route.js:144:13)
    at next (C:\Users\slb\Documents\Projects\remix-sse-wehriam\packages\example\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\route.js:140:7)`

**Comment by StevenBendell** [comment]
Resolved by upgrading Node to version 18
https://developer.mozilla.org/en-US/docs/Web/API/TransformStream
